name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: init hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV
      
      - name: lint
        run: ./bin/cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: init hermit
        run: ./bin/hermit env --raw >> $GITHUB_ENV
      
      - name: test
        run: ./bin/cargo test
